FROM python:3.12-slim

WORKDIR /app

# Copier le code source
COPY . .

# Mettre pip à jour et installer les dépendances
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Rendre le script exécutable
RUN chmod +x run.sh

EXPOSE 5000

CMD ["./run.sh"]
